apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ include "rabbitmq.name" . }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}-management
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: {{ include "rabbitmq.name" . }}-management
      port: 15672
      targetPort: 15672
      protocol: TCP
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
